### ISSUE TITLE
No Communications

### ISSUE THREAD

**Issue by tibesararchives** [OllieWP/ollie#134]
It appears the Ollie theme author is busy with more important matters. His/her continued non-communications about issues we have submitted on Github is frustrating.

We are going to look for a new block theme that has better communications and support.

Good luck guys!

**Comment by mikemcalister** [comment]
Hi Marcus,  

That is correct, I am busy with more important matters — **I've just welcomed my first son into this world** and I'm busy caring for him. Your arrogance and entitlement are incredibly off-putting.

I've put **hundreds** of hours into creating Ollie and getting it on the repo for everyone to use and learn from. On top of that, I've spent **hundreds** of hours creating written and video content for everyone to learn how to use modern WordPress and the Ollie theme. **I've done all of this for free. For you.** You've paid precisely $0 for this, and somehow you find the gall to come in here with this kind of entitlement.

This isn't the first time you've come at me in an aggressive way because you didn't get what you want. Respectfully, if this is how you treat people, I'd rather you find some other theme to use. We're more than happy to help folks, but this is a labor of love right now. Be resourceful, ask around, make some friends in the community, get some assistance from the many folks who are building with block themes. Everyone else seems to be figuring it out without the negativity. 

I should also mention, I've been incredibly generous with you in the past, answering dozens and dozens of support tickets with my Array theme collection. Nothing about my history of generosity with you deserves this kind of commentary.

**Comment by tibesararchives** [comment]
I have been helping you with submitting issues about the Ollie theme. I thought that was the purpose of this channel. Apparently you don't want to be informed about issues, and when informed about issues you name call "arrogrance and entitlement". All I said is you are not communicating back when issues are submitted. You go off on a tangent about your personal life and then claim falsely that I am being aggressive. I guess when I submit issues and then cite non-communications back; I am being "aggressive". "Everyone else seems to be figuring it out without negativity" - screw you. I won't submit anymore issues to help you identify problems with your new Ollie Pro project. I don't want to ruffle your feathers snowflake.

**Comment by mikemcalister** [comment]
Have a good life, Marcus! 👋

**Comment by mikemcalister** [comment]
PS all of your tickets have been answered. You're welcome!
