### ISSUE TITLE
Mobile Menu Close Button 

### ISSUE THREAD

**Issue by jamesgiroux** [OllieWP/ollie#147]

**Comment by jamesgiroux** [comment]
So, I clicked enter accidentally. Sorry about that. I've noticed that the mobile menu close button takes on some styling that makes it hard to read.

![CleanShot 2024-04-05 at 12 12 35@2x](https://github.com/OllieWP/ollie/assets/1839527/4b046d8f-7c07-407f-b121-35ea2c5ec195)

I'm using a dark tertiary colour and that appears to be used for the button color background but the text color is our regular text color. I guess usually this isn't a problem but there are no options to change the color of the close button specifically in the block. 

I'm hoping in a future release this might be something that I can do. Not sure if this is Ollie or WP related but just thought I'd provide the feedback.  :-D

**Comment by mikemcalister** [comment]
Hey James, 

Sorry for the late response. This is an unfortunate shortcoming of the navigation block. It _still_ doesn't have sensible customization yet. The quick fix would be to revert the tertiary color back to a lighter color, since it is used throughout the theme in that way and then customize this menu button with a touch of CSS if needed.
