### ISSUE TITLE
Setup wizard does not launch

### ISSUE THREAD

**Issue by tigerhobbes25** [OllieWP/ollie#160]
**Describe the bug**
I installed and activated the Ollie scheme from within Wordpress. But the setup wizard (which was one of the main reasons why I am interested in Ollie as a noob in WP) did not launch as shown in your youtube tutorial.

I then deleted my WP installation completely and set it up again, thinking that some previous activities with the 2024 scheme may have somehow impeded Ollie to launch its wizard. But again the same, there was no wizard or prompt at all when I activated Ollie.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 124.0.6367.156

**Comment by itsic7** [comment]
The setup wizard had to be removed from theme and moved to a companion plugin in order to comply with WordPress theme standards. Mike posted about it here: https://olliewp.com/the-ollie-block-theme-is-now-available-on-wordpress-org/. Here is the link to the companion plugin: https://github.com/OllieWP/ollie-pro

**Comment by tigerhobbes25** [comment]
Great, thanks for quick reply and the hint! Completely missed that.
