### ISSUE TITLE
Make header sticky

### ISSUE THREAD

**Issue by zu** [OllieWP/ollie#19]
**Describe the bug**
Although I defined the position of the first group in the header as sticky, the header doesn't become sticky.
I have had similar problems with other themes, therefore I'm not sure if it's a bug or a feature or something I need to add.

**To Reproduce**
1. Go to the Site Editor (Appearance  > Editor)
2. Choose the template part "Header" and start to edit it
3. Select the top group block and select position Sticky
4. Save

**Expected behavior**
The Header should now be sticky and stick at the top of the screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Microsoft Edge, Google Chrome, Firefox
 - Version: newest

![screenshot-sticky-backend](https://user-images.githubusercontent.com/147629/229604911-aa7458eb-1fa5-42e8-a961-a095426af9f2.png)

![screenshot-sticky-frontend](https://user-images.githubusercontent.com/147629/229604968-0d225b39-117b-4062-aafc-acf4cebd5704.png)

**Comment by mikemcalister** [comment]
Hey there, thanks for sending this along. I think I see what's happening here, and as you expect, it's a core thing. 

The sticky option only shows on elements are a top-level item on the page, meaning they aren't nested in groups. The header template part seems to be acting as a container element, and therefore the sticky option doesn't show. If you click on the group inside the header template part, it also doesn't show because it's nested. 

However, as you'll see in the video below, once I detach the template part, the header group becomes a top level item, and the sticky position does work. 

https://user-images.githubusercontent.com/1415737/230186739-3e035b2e-e643-4678-adbc-5b7ec523ec70.mp4

This position feature is relatively new, and I'm sure there will be some fast follow improvements. I'll keep digging in and see if there's a way to make this work as is.

**Comment by mikemcalister** [comment]
Just a quick follow up here, if you group the header template part into a new group, you can apply the sticky position to that.

https://user-images.githubusercontent.com/1415737/230190449-1b8aac1c-5af2-49c5-8c0f-457c53ca88a9.mp4

**Comment by zu** [comment]
Thanks Mike

If I understand you and the state of sticky correct, it's (at least for now) not possible to set position sticky at the top-level group of the header template part as the header template part becomes itself a nested element in the template and is then not the top-level group anymore.

Therefore, I need to group the header template part itself within every template where it's used and can then set it to sticky.

And since this additional group inherits the "Inner blocks use content width" I have to set it to full width or deactivate "Inner blocks use content width".

It's a bit elaborate, but it works now.
Thanks again for showing and for OllieWP! (Really great theme and great patterns)

Next step would be to animate the header smoothly to a smaller size (including minimizing the logo) before making it sticky.

But this effect can wait ;-)

**Comment by mikemcalister** [comment]
Yup that's right, as far as I can tell. I'll close this for now, but will keep an eye on this in core and if there's anything I can do in the theme to help, I certainly will. I have some ideas of how to animate this, and may include a sticky header in the theme. 😎
