### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by moggiex** [OllieWP/ollie#27]
Howdy Mike,

Some feedback on the theme, do note this is the first time I have played with a block theme, so there might be some "n00b" thrown in here. 

Oh and I found the theme via this [video](https://www.youtube.com/watch?v=CJVXnY-B81Q) on YT (always nice to know where things are found).

A few things after playing with the theme for the last hour or so.

- It's fast. 
Fast enough for me to consider using it on one of the main sites, nice! (nginx, w3 total, varnish, ewww images and some other tweaks). Consistently hitting 90/96/100/92 even after adding custom plugins, an off-the-shelf which is a bit "fat" and a ton of data to a test site.

- Side Bar 👍 
I know these are not fashionable at the moment, but it would be nice to see a sidebar page/single template come out of the box (added my own as a template part) because frankly they still work and work well for associated content items.

- Theme file override.
I'm guessing this is WP reacting to the theme being a block theme, it appears to remove the theme file editor that's a bit of a pain as I normally use that for small hacks and then migrate over to a dedicated custom plugin for things that work well. Would be nice to get that back.

- Theme colours
Not everyone's cup of tea for the default ones. Tried adding the [block editor colours](https://en-gb.wordpress.org/plugins/block-editor-colors/) plugin, not really compatible. Would be nice to set some basic colours somewhere and those be used by default to override the standard themes included.

- You mentioned videos...
In your video [here](https://www.youtube.com/watch?v=pWpnMD2MX7w) you mention more videos being added, would it be an idea to include these in the theme admin somehow as a library? Not seen that done before and would be extremely useful (help where and when it is needed and no external searching. Plus they see you more :P ).

- Child Theme
Are these needed for block themes? I instinctively created a child theme and have been editing that, if these are still the best way forwards, can we have a child theme provided, please?

- Separate Demo Page
The main "Frontpage" was extremely useful to work out how you had done certain things. It would be nice if there was a duplicate or showcase template that I we could go back to to find out how certain things are done later. I've edited mine already and would probably need to install it on a demo site to work out how TF some things were done previously

- Export Option
Probably my newness to block themes here, but how would one make a copy of existing modifications and transfer those to another site? Not looked for a plugin for this, but and export/import option would be nice.

Hope the above help, ignore anything as you see fit :P

M

**Comment by moggiex** [comment]
* Found the export option :)

**Comment by moggiex** [comment]
Thinking about this over night Mike

1. The ability to easily add to site colour themes would be most helpful
2. I missed the "sticky" header option that's not present in the theme currently 
3. And I just miss the side bar, but that IS easily added.

M

**Comment by moggiex** [comment]
3 days later.... Moved from what I felt was a well-tuned, heavily modified site using Enfold (which I've used for years on multiple sites), to using OllieWP. **Learnt a lot!**

Today most pages are hitting +80 for performance in pagespeed.web.dev, even on the heavier pages with a "fat" plugin being used. Up from an average of 57 site wide. 

Some feedback so far:

1. Really missing the sidebar out of the box. Have added my own. Would like to see that as an option
2. Hardly ideal, but this saved me from going back to a classic theme [X3P0 Legacy Widget](https://wordpress.org/plugins/x3p0-legacy-widget/)

Minor gripes:

1. Had to move custom functions to a plugin, seems to be a side product of using a block theme which is quite annoying. The same for the disabling of theme editing and plugin editing (even after trying to override in the wp-config). 
2. Would like a sticky header bar

Have not looked at making a child theme yet, that's my only lagging concern is keeping the theme updated against any changes to its core (a tomorrow problem). 

Really pleased with the results Mike

**Comment by mikemcalister** [comment]
Thanks for all this excellent feedback, Matthew! 

> Really missing the sidebar out of the box.

I'll get a pattern or template in the theme for this. Stay tuned! 

> Would like a sticky header bar

Sticky headers are possible now, but they can be tricky because of the lack of responsive controls in core. I'm trying to avoid adding too much custom code in favor of core solutions, but unsure how long that could take. I've seen previews of responsive settings like "hide on mobile" which could help with the sticky header. I'll see what I can do though! 

> Have not looked at making a child theme yet

Yeah child themes certainly still have a utility for customizations. To be honest, I haven't experimented a ton with this yet either. However, the OllieWP.com site is running a child theme on top of the Ollie theme, and I haven't had any issues yet.

**Comment by gregfarries** [comment]
Speaking of using a child theme with Ollie... I've attempted to use the Create Block Theme WP plugin to create a child theme of Ollie, and it doesn't seem to work.

<img width="667" alt="Screenshot 2023-05-12 at 4 30 24 PM" src="https://github.com/OllieWP/ollie/assets/5964105/464e858e-5918-4c9a-8a7d-1916b930aa75">

I get an error stating the parent theme, Ollie isn't installed.  

I'm using the "Create child of Ollie" functionality in Create Block Theme, and this functionality works when making a child theme of say, Frostwp...

Here is the exported folder structure when creating a child of Frost:

<img width="298" alt="Screenshot 2023-05-12 at 4 33 48 PM" src="https://github.com/OllieWP/ollie/assets/5964105/7847cd08-bc81-413d-bb04-f9efe36e6f05">

But this is what happens when creating a child of Ollie:

<img width="319" alt="Screenshot 2023-05-12 at 4 34 51 PM" src="https://github.com/OllieWP/ollie/assets/5964105/a753dc54-78d2-4129-8b5d-9200a07d0efd">

Any ideas?

Thanks!

And this might be a separate issue from above, so if you want me to create a new issue thread, I can.

**Comment by mikemcalister** [comment]
Closing up this ticket. We've addressed many of the great bits of feedback here and have the rest logged for future updates!
