### ISSUE TITLE
Shouldn't the Front Page content be in the page instead of the template?

### ISSUE THREAD

**Issue by Ren2049** [OllieWP/ollie#30]
I was today years old when I've learned that not including a query loop on template pages and pulling in the content from the page itself is considered a mistake with block themes. Jamie from Pootlepress also touches this in his latest [YT video](https://www.youtube.com/watch?v=RsFMHafzUz4). 

https://github.com/WordPress/gutenberg/pull/49904

https://core.trac.wordpress.org/ticket/58154

**Comment by mikemcalister** [comment]
Hey there, I'm continuing to watch how this evolves. I've had chats with Jamie and several others and there isn't a concrete consensus on what the paradigm should be here.

On one hand, using the query loop might be traditionally more "correct" but it makes creating a homepage (or other page with a pre-made design) far more unintuitive for most folks. They have to create a page, apply the template, build their content or insert it via a pattern, and publish. On top of that, the admin view and front end view can be a little disconnected (like having the big page title above your design in the editor, but it doesn't appear on the front end because of the template).

On the other hand, templates with the design already applied are instantly familiar and ready to edit. They are not inundated with a whole process just to create a page. The concern is that their page isn't being saved as a traditional page, it's being saved to the db as a customized version of the template. This could be problematic now, but with template revisions coming, this may not be such a big concern. 

At any rate, I'm trying to figure out the best way to pull all this stuff together in an intuitive fashion, and that might mean rethinking the traditional approach in favor of something more user friendly. I'm willing to experiment to see.

**Comment by Ren2049** [comment]
Tried the "clean templates way" yesterday in TT3 in my current localwp test site using the post-content block. Why the heck is it even named this way and not just  "content" block if it's supposed to be the way things should work for pages too?

Building pages in the text editor unable to exit content width (in my case for blog posts it's set to a narrower width) isn't fun, equally like it isn't fun to write posts in a wide content width. I think editing the templates for page content and using the text editor for posts is still the way to go! 

I also think that a strict hierarchy of page/template > section/template-part > pattern > blocks wold be really helpful. 

Gosh, this whole block editor thing still feels like a complete trainwreck. Maybe we can leverage AI to rewrite this whole thing haha.
