### ISSUE TITLE
Ollie Blueprint

### ISSUE THREAD

**Issue by argidenise** [OllieWP/ollie#33]
Hello there!

I wanted to express my gratitude for this amazing theme. I stumbled upon it on Twitter, and I must say, it's my first time experimenting with a block theme for WordPress.

I've noticed that the version of the theme provided in the Localwp Blueprint is not up to date. I attempted to update it using the latest version available on GitHub, but unfortunately, it doesn't align with the current version of the theme in the Localwp Blueprint.

Secondly, I encountered a problem with the [Blog page](https://demo.olliewp.com/blog/) on the Ollie demo. It doesn't seem to be working as expected.

Thank you!

**Comment by argidenise** [comment]
Is there a way to automate the process of extracting the first paragraph of each post for the "Read More" button? It becomes tiresome to manually edit each post and add the "More" block.

**Comment by argidenise** [comment]
Could the recommended posts at the bottom of the blog post be different or not repeated?
![Web capture_14-5-2023_232516_ollieblueprint local](https://github.com/OllieWP/ollie/assets/127620618/70d3f7dc-65f1-4b22-a9fc-66c7e988c394)

**Comment by mikemcalister** [comment]
Hey there, 

You can edit the Index template to show the excerpt instead of the post content. See the video below for how to do that. 

https://github.com/OllieWP/ollie/assets/1415737/dcecad96-7e87-474c-8aeb-7ffe486516c4

The posts at the bottom of blog posts are showing the 3 latest posts right now. Unfortunately, the core post block doesn't have a ton of options yet. You could also remove that via the Single template if you don't like how it works.

I'll have to update the Local blueprint, thanks for the heads up! The blog page should also be working now on the demo. I'll be releasing a new update shortly with some fixes to these things.

**Comment by argidenise** [comment]
Thank you so much! Will wait for your next Ollie release.

**Comment by argidenise** [comment]
I appreciate the release of version 0.1.3. I'm also looking forward to an update for the localwp blueprint. Thank you, Sir Mike!
