### ISSUE TITLE
Wrong spacing e.g. before lists with Gutenberg or WP 6.3-beta active

### ISSUE THREAD

**Issue by TobiasBg** [OllieWP/ollie#52]
**Describe the bug**
On WP 6.2.2, the spacing between e.g. paragraphs and lists (to my eye correctly) looks like this:
<img width="206" alt="Bildschirmfoto 2023-07-08 um 21 22 57" src="https://github.com/OllieWP/ollie/assets/155439/4eb7863b-6a49-4d10-b31c-2533262bbff9">
On WP 6.3-beta or WP 6.2.2 and the Gutenberg plugin, the spacing is gone (which looks ugly):
<img width="134" alt="Bildschirmfoto 2023-07-08 um 21 23 59" src="https://github.com/OllieWP/ollie/assets/155439/e17c19a8-daa2-4251-9055-37681b7bfac2">

**To Reproduce**
1. Install WP 6.2.2 and Gutenberg.
2. Add this to a post or page:
```HTML
<!-- wp:paragraph -->
<p>Paragraph</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>Text</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Text</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Text</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
```
3. Check the spacing with and without Gutenberg active.

**More Info**
A brief inspection with the developer tools shows that the CSS code
```CSS
body .is-layout-constrained > * + * {
     margin-block-start: var(--wp--preset--spacing--medium);
     margin-block-end: 0;
}
```
doesn't seem to be part of the page anymore, with WP 6.3-beta or Gutenberg.

**Comment by verquist** [comment]
Hi Tobias,

I'm using Ollie + WP 6.2.2. I'm not seeing this. With WP 6.2.2, you no longer need the Gutenberg plugin. The block editor is built into WordPress.

Maybe try uninstalling the Gutenberg plugin?

Cheers,
Jim

**Comment by TobiasBg** [comment]
Hi @verquist,

thanks for taking a look at this!

Correct, this does not happen with WP 6.2.2 without the Gutenberg plugin.

Now, in my case, I'm not using Gutenberg to _get_ the block editor, but to benefit from its latest features (like new blocks, like the Details or the Footnote block), as the plugin is still the place where future block editor development is happening. In particular, what's in Gutenberg now will be in WordPress Core in the future.

Thus, the issue that shows with WP 6.2.2 and Gutenberg will also show in WordPress 6.3 (without Gutenberg) once it's shipped in August (and it shows in the current beta versions already).

Best wishes,
Tobias

**Comment by verquist** [comment]
Hi Tobias, I kind of suspected you knew what you were doing with the Gutenberg plugin. :-)

Sounds like you found a bug in WP 6.3-beta. Thank you for making sure these get discovered before WP 6.3 is released, so people like me don't run into them.

Best of luck!
Jim

**Comment by mikemcalister** [comment]
Hey folks, thanks for taking a look at this. I've recently pushed a fix to the develop branch that will fix this. I've tested it against the 6.3 beta via the beta tester plugin. I'll get another release ready with this fix.

@TobiasBg on this comment: 

> In particular, what's in Gutenberg now will be in WordPress Core in the future.

Just a heads up that that's not always necessarily true. Some experimentation happens in Gutenberg that ultimately doesn't make it to core. Because Gutenberg is constantly in flux, I don't recommend average folks have it active when doing their day to day activity in WordPress. I don't even have it active usually! 

The main reason is because there is such a flurry of active development in there, visual quirks are introduced that interfere with the block editor, etc. So it can make it look like your WordPress install is goofy. 

Also, because Gutenberg changes the interface ahead of core, as a product maker, you end up having to support two interfaces (Gutenberg's and current WordPress core's) if a bunch of folks are working with Gutenberg active on the daily. 

Anyway, just some rambling thoughts from someone building a product on the bleeding edge! 😅
