### ISSUE TITLE
Replace Header or Footer option

### ISSUE THREAD

**Issue by Leemshop** [OllieWP/ollie#76]
Hello Mike,
thanks very much for OllieWP and your tutorials. It's really very helpfull.
Yersterday I played around a bit with Ollie on Instawp. At some point I tried to replace a header in a template, but got stuck there. Partly because I don't have very much experience with blockthemes. 
A search on Google and one of your own tuturials learned me that there is or was an option "Replace". It is still there in Twenty-Twentythree but I can't find that option in OllieWP.
Are there other ways to replace a templatepart like a header? Maybe even in the menu in the image I attached?
![Schermafdruk van 2023-09-03 12-27-23](https://github.com/OllieWP/ollie/assets/24974882/a01cdaee-a3bf-40ee-a23e-5fb5dad94f0d)

Kind regards
Geert de Bock

**Comment by Leemshop** [comment]
Maybe the menu in english is making it more clear!
![Schermafdruk van 2023-09-03 12-32-50](https://github.com/OllieWP/ollie/assets/24974882/ed1f0741-b86b-4927-ada9-95dee382985e)

**Comment by mikemcalister** [comment]
Hi there, 

I'm still looking into this, but I believe this is a core bug. The issue seems to happen sporadically on my end. Sometimes I see Replace and sometimes I don't. I don't think there's anything in the theme causing this, as we don't have control over the menu items like that. I'll keep looking into it and report back anything I find. 

In the mean time, I've found that clicking out of the menu and clicking back in can sometimes help.

**Comment by mikemcalister** [comment]
This should be fixed with the latest release of the theme, version 1.0.3. I did notice other folks mentioning this on other themes, so if it still pops up, I can take a closer look.
