### ISSUE TITLE
Box shadow settings for core/group only work when core/columns blok is used

### ISSUE THREAD

**Issue by tiborp** [OllieWP/ollie#78]
I noticed when setting the box shadow when using the `blog-post-columns` pattern, this will only work when there is also a core/columns block being used on the page, since the blog-post-columns pattern does not use a column block by itself.

You can reproduce this by removing the footer (which has columns) from the index template and then add the box shadow to the post group.

I found out when using the block-post-columns pattern and the footer-minimal (which does not have columns) in a template.

Hope this helps.

**Comment by mikemcalister** [comment]
Hey Tibor, 

Nice catch! The official box shadow component will be coming to WordPress 6.4 (early November), so instead of adding a temporary fix, I'm going to hold off and implement the shadow properly so it can be modified via the UI. 

In the mean time, you can fix this by adding the following CSS to your site via the Additional CSS field in the global styles panel. That way, this CSS is always loaded and is available whether there is a column or not. 

<img width="742" alt="Screenshot 2023-09-13 at 3 00 26 PM" src="https://github.com/OllieWP/ollie/assets/1415737/4cece78a-1fd8-4f63-b75a-8558478d8eba">

```
.is-style-column-box-shadow {
	box-shadow: 0px 8px 40px -20px rgb(21 14 41 / 12%);
	transition: .4s ease;
	order: 1;
}

.is-style-column-box-shadow:hover {
	box-shadow: 0px 12px 60px -20px rgb(21 14 41 / 16%);
}
```
