### ISSUE TITLE
There is no Ollie Theme Setup wizard

### ISSUE THREAD

**Issue by annalyle** [OllieWP/ollie#98]
**Describe the bug**
I installed Ollie on https://dev1.muchow-webdesign.de
I can't find the Ollie Theme Setup wizard

**To Reproduce**
1. Go to 'https://dev1.muchow-webdesign.de/wp-admin/site-editor.php'
2. See screenshot screen1.png

**Expected behavior**
Want to see the Button "Go to the Setup Wizard" (like screenshot2.png)

**Screenshots**
 screen1.png
![screen1](https://github.com/OllieWP/ollie/assets/148250329/6a1ddc13-fe14-478e-a662-16da3ebd5e0a)

 screen2.png
![screen2](https://github.com/OllieWP/ollie/assets/148250329/f028b8e8-3fac-4bd5-987f-f84c9a9b931f)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser firefox
 - Version 118.0.2 (64-Bit)

**Comment by mikemcalister** [comment]
Hi there, apologies for the confusion. We had to remove the Ollie onboarding wizard from the theme in order to get the theme listed on the WordPress.org directory. You can read more about that [on the Ollie blog](https://olliewp.com/the-ollie-block-theme-is-now-available-on-wordpress-org/).

However, we'll be bringing back the dashboard and wizard via a plugin, and it will be available soon!
